### ISSUE TITLE
typo in documentation of frequency_impulse_response() and frequency_filter()

### ISSUE THREAD

**Issue by babua** [magenta/ddsp#107]
In `core.frequency_impulse_response()` and `core.frequency_filter()`, the [documentation](https://github.com/magenta/ddsp/blob/8075aba302295b2cf546a02c2efdced60f689b78/ddsp/core.py#L807) states:

`The frequencies of the last dimension are ordered as [0, f_nyqist / (n_frames -1), ..., f_nyquist], here f_nyquist is (sample_rate / 2).`

Shouldn't this be `f_nyqist / (n_frequencies -1)` ?

It didn't make sense to me signal-processing-wise, so I think it's a typo?

**Comment by jesseengel** [comment]
yup, good catch! Want to make a PR?

**Comment by babua** [comment]
Thank you for the offer, I think it's easier if it goes in from your side? That being said, I'll do it if you prefer that I do it.

**Comment by jesseengel** [comment]
No worries, thanks for pointing it out.
