### ISSUE TITLE
train_autoencoder.ipynb Colab Error

### ISSUE THREAD

**Issue by ioannist** [magenta/ddsp#134]
Colab notebook of train_autoencoder.ipynb returns error in first step

`  Building wheel for crepe (setup.py) ... done
  Building wheel for avro-python3 (setup.py) ... done
  Building wheel for oauth2client (setup.py) ... done
  Building wheel for hdfs (setup.py) ... done
ERROR: pydrive 1.3.1 has requirement oauth2client>=4.0.0, but you'll have oauth2client 3.0.0 which is incompatible.
ERROR: chainer 6.5.0 has requirement typing-extensions<=3.6.6, but you'll have typing-extensions 3.7.4.2 which is incompatible.
ERROR: apache-beam 2.22.0 has requirement future<1.0.0,>=0.18.2, but you'll have future 0.16.0 which is incompatible.`

**Comment by jesseengel** [comment]
This was cross posted on the magenta github: https://github.com/magenta/magenta/issues/1749

Seems like its a beam requirements issue. Adam can you take a look?

**Comment by adarob** [comment]
This is safe to ignore.

**Comment by jjlcolab** [comment]
Please have a look at the actual link Jesse posted above. The main problem was that the "Preprocess raw audio into TFRecord dataset" cell crashes the whole thing. 

It may not be related to the beam requirements then, but the main point in my raised issue was that the train_autoencoder.ipynb was not working.

Anyways, please mention in the notebooks if some errors are safe to ignore or better yet add ignore warnings to the actual code.
