### ISSUE TITLE
Timbre Training - Tips for ML-dummies

### ISSUE THREAD

**Issue by ioannist** [magenta/ddsp#143]
I have a software development and music background, but I lack knowledge in ML. I was wondering if the team could provide some general directions in regards to the training samples we should feed train_autoencoder.ipynb to get the best results.

In particular:

- Should the training audio include as many notes and as many octaves as possible?
- Should the audio include various articulations of the notes at different velocities?
- Does it matter if the training audio is not musical? Can we just include scales?
- Should we convert the audio to 16K before loading for training? How many bits?
- Assuming we load audio with samples (not music), should we make each sample 4 seconds (starting at time 0:00) to match the chunk size, or it does not matter?
- What is the intuition behind pitch and loudness in timbre_transfer? Should we be trying to match the pitch and loudness level of the source to get the most convincing results?

I think that answers to these questions will help me and others get a better sense of how it all works. In the meantime, you have convinced me to learn ML :)

**Comment by jesseengel** [comment]
Hi! Sounds like you're off to a good start.

> * Should the training audio include as many notes and as many octaves as possible?

Yup, although you should try to keep focused to a single instrument with the current models.

> * Should the audio include various articulations of the notes at different velocities?

Yup, more the better.

> * Does it matter if the training audio is not musical? Can we just include scales?

That should be fine, but the models will really shine with natural musical input.

> * Should we convert the audio to 16K before loading for training? How many bits?

The training script should handle that for you (it will convert to 16kHz for the time being).

> * Assuming we load audio with samples (not music), should we make each sample 4 seconds (starting at time 0:00) to match the chunk size, or it does not matter?

The training script will also handle that for you in the creation of the dataset.

> * What is the intuition behind pitch and loudness in timbre_transfer? Should we be trying to match the pitch and loudness level of the source to get the most convincing results?

The intuition is finding a small set of easy to interpret controls that we can extract from audio inputs that capture the esseential elements of variation. Yes, you will get the most convincing results by best matching pitch and loudness, the timbre_transfer model will try to do a bit of this automatically, but matching inputs will achieve best results.

**Comment by ioannist** [comment]
Super helpful! Thanks a lot.
