### ISSUE TITLE
gin binding with my own tfrecord files

### ISSUE THREAD

**Issue by skokoh** [magenta/ddsp#145]
Hi,

could you share some examples how to bind tfrecord files to gin with my own data?
More description of creating my own tfrecord.gin in tutorial would be really appreciated.

Many thanks!

**Comment by jesseengel** [comment]
Hi! Thanks for the feedback. More tutorials would be great for sure, and we'll try to get there as the library matures. You shouldn't actually have to make your own gin file, as you can pass in flags to configure gin, the key one is 

`--gin_param="TFRecordProvider.file_pattern='/path/to/dataset_name*.tfrecord'" `

Alternatively, you can just add the line:
`TFRecordProvider.file_pattern='/path/to/dataset_name*.tfrecord'`
to your new gin file based on tfrecord.gin to make that gin file specific to a single dataset, and then you don't need to pass the other flag.

**Comment by adarob** [comment]
Opened #146 to track adding a tutorial.
