### ISSUE TITLE
calling astype on python list in timbre_transfer.ipynb

### ISSUE THREAD

**Issue by Forevian** [magenta/ddsp#15]
`audios[0:1].astype(np.float32)` in the basic timbre_transfer.ipynb does not work, as `audios` is a list.
`audios[0].astype(np.float32)` works.

**Comment by Forevian** [comment]
Or rather stg like `np.asarray(audios[0:1]).astype(np.float32)`

**Comment by jesseengel** [comment]
Thanks for pointing this out! Just a few stray bugs from the upgrade to tf2. I believe this commit fixed it. https://github.com/magenta/ddsp/commit/f903f3f42e4a88d01682022ade4351ba73164618
