### ISSUE TITLE
evaluate/sample mode question using my own dataset

### ISSUE THREAD

**Issue by skokoh** [magenta/ddsp#151]
Hello!

I am trying to use my own dataset for training/evaluation/sampling on ddsp_run.py.

Could you share some examples of how to sample after training? Based on the description of README file, I need my own model's gin file for sampling, but in ddsp_run.py or example code, there is no parameter for getting my model gin file.

> When training, all gin parameters in the operative configuration will be saved to the ${MODEL_DIR}/operative_config-0.gin file, which is then loaded for evaluation, sampling, or further training. The operative config is also visible as a text summary in tensorboard. See this doc for more details. 

```

================================================================================
For evaluation and sampling, only the dataset file is required.
================================================================================
ddsp_run \
--mode=eval \
--alsologtostderr \
--save_dir=~/tmp/$USER-ddsp-0 \
--gin_file=datasets/nsynth.gin

ddsp_run \
--mode=sample \
--alsologtostderr \
--save_dir=~/tmp/$USER-ddsp-0 \
--gin_file=datasets/nsynth.gin

```

Any information would be appreciated.
Thank you so much.

**Comment by jesseengel** [comment]
Hi!

All of your model configuration should be saved in the save_dir, in a file called something like `operative_config-0.gin`. So it will be automatically loaded when passing the `--save_dir` flag.  Tou can always pass in more gin files by adding additional `--gin_file` flags to your commands, or specific config params by `--gin_param`, that should override any options in your operative config. 

FYI, Those eval and sample jobs will just add tensorboard summaries, which you can then inspect and listen to.

**Comment by skokoh** [comment]
Thank you for the explanation. Adding additional --gin_file flags and --gin_param works! Appreciate it.
