### ISSUE TITLE
Loss functions in practice

### ISSUE THREAD

**Issue by Forevian** [magenta/ddsp#160]
Could you please write a few lines (maybe add it as code comments or readme documentation) about when to use the various loss functions, what are they good for in the context of ddsp? (ie. the new cumsum)?

**Comment by jesseengel** [comment]
Sorry about the confusion, just one of the challenges of having an actively experimental codebase. I try to keep the more experimental functions out of the core `ddsp/` part and in training, but those slipped through. That angular_cumsum is to squash a bug that shows up when you generate long samples (>10 seconds). I needed to push it to the public repo as we're looking at using it in our integration work of ddsp in javascript (tf.js) and that was a bug that needed squashing. 

Best,
Jesse
