### ISSUE TITLE
Dockerfile for training and development

### ISSUE THREAD

**Issue by maxardito** [magenta/ddsp#176]
Howdy! I'm in no way a DevOps expert, but I thought that a cool feature might be a dockerfile for training `ddsp_run` in the cloud. Basically something like [this tutorial](https://cloud.google.com/ai-platform/training/docs/custom-containers-training) but with `ddsp_run` and audio files in a gs bucket. 

My thought is that it might be neat to have one dockerfile for quick neural net training that just installs ddsp from pip, and then another that copies a user specified version of the repo or a fork of the repo for training. Again, I'm not a docker expert, but I've been playing with it over the past month or so and thought it might be useful to organize both user and development pipelines.

I'm hacking away at something at the moment that I could PR in a few weeks y'all would like 🐳 🐳 🐳

**Comment by werkaaa** [comment]
Hello! Together with @ana-simionescu we are working on this feature as our STEP Internship project. You can take a look at each of our branches in the [project repository](https://github.com/googleinterns/ddsp-docker) to see what we have managed to do so far. We would love to know more about your work! 🐳 🐳 🐳

**Comment by maxardito** [comment]
@werkaaa How exciting! Can't wait to try out what y'all come up with.

I'd be happy to talk about some of my work via email (address is on my github page), and I'll touch base here again if I come up with any contribution

**Comment by ana-simionescu** [comment]
@maxardito Hi! @werkaaa and I wanted to let you know that our project is completed. The docker training configuration ca be found in this repo [here](https://github.com/magenta/ddsp/tree/master/ddsp/training/docker). We've also created a web interface to make launching the training even easier. It is hosted on our project's github pages [here](https://googleinterns.github.io/ddsp-docker/).

**Comment by maxardito** [comment]
@ana-simionescu So cooool! Awesome work, can't wait to play with it 🎉
