### ISSUE TITLE
Issues with dependency versions and TF 2.3.0

### ISSUE THREAD

**Issue by maxardito** [magenta/ddsp#177]
I tried building ddsp with `python setup.py install` today and ran into a few dependency issues. I'm not entirely sure whether they have to do with TF 2.3.0 coming out or something else, but the last time I built ddsp, it was before 2.3 and it worked. 

Here are the three inconsistencies

```
error: scipy 1.5.2 is installed but scipy==1.4.1 is required by {'tensorflow'}
...
error: numpy 1.19.1 is installed but numpy<1.19.0,>=1.16.0 is required by {'tensorflow'}
...
error: protobuf 4.0.0rc2 is installed but protobuf<4,>=3.7 is required by {'tensorflow-metadata'}
```

In setup.py I was able to build everything with the following

```
install_requires=[
        'absl-py',
        'crepe>=0.0.11',
        'future',
        'gin-config>=0.3.0',
        'librosa',
        'pydub',
        'mir_eval',
        'numba < 0.50',  # temporary fix for librosa import
        'numpy==1.18.0',
        'scipy==1.4.1',
        'six',
        'tensorflow',
        # TODO(adarob): Switch to tensorflow_datasets once includes nsynth 2.3.
        'tfds-nightly',
        'protobuf==3.9.2'
    ]
```

But then got this error message once I ran `ddsp_prepare_tfrecord`

```ModuleNotFoundError: No module named 'apache_beam'```

**Comment by jesseengel** [comment]
Thanks for the heads up. Beam requires `pip install -U ddsp[data_preparation]`. You can find that [here](https://github.com/magenta/ddsp/blob/master/setup.py#L59) but we should make that in the main README.md.

**Comment by maxardito** [comment]
Works perfectly now, thanks @jesseengel !! 

P.S. loved your interview on Holly Herndon's podcast ☺️
