### ISSUE TITLE
ddsp-inv learned f0 weird

### ISSUE THREAD

**Issue by james20141606** [magenta/ddsp#186]
Hey, I have tried the new DDSP-inv model on human voice dataset. The encoded f0 looks much better on some of my data. But sometimes it has an "opposite" prediction like this:

![image](https://user-images.githubusercontent.com/14315324/90351813-5f867500-e00f-11ea-874f-8267acb82a5d.png)
the ddsp f0 are from ddsp-inv. if I remember clearly, this also happened sometimes in previous ddsp model's result

I wonder why that happens, and if we could resolve this by synthesizing more data with f0 sampled from my own data.

**Comment by jesseengel** [comment]
Hi, you probably want to try the fine-tuned models. I just added a colab notebook demo here for pitch detection
https://github.com/magenta/ddsp/blob/master/ddsp/colab/demos/pitch_detection.ipynb

You can also download the pretrained models from the paper README here if you want to run them locally:
https://github.com/magenta/ddsp/tree/master/ddsp/training/gin/papers/icml2020

**Comment by james20141606** [comment]
Thanks for the reply! You mean I could try the finetuned model on URMP dataset? Currently I apply the pretrained model on synthetic and finetune on human voice dataset. I will try to use model finetuned on URMP, finetune on my dataset and observe the result. Thanks!

**Comment by jesseengel** [comment]
Finetuning from the pretrained synthetic dataset is still pretty expensive (400k+ iterations, batch=64, multi-GPU). So we've provided three finetuned models (on three different datasets) that you could work with: 

[URMP](http://www2.ece.rochester.edu/projects/air/projects/URMP/annotations_5P.html) ([ckpt](https://storage.googleapis.com/ddsp-inv/ckpts/urmp_ckpt.zip)),
[MDB-stem-synth](https://zenodo.org/record/1481172#.Xzouy5NKhTY) ([ckpt](https://storage.googleapis.com/ddsp-inv/ckpts/mdb_stem_synth_ckpt.zip)),
and [MIR1k](https://sites.google.com/site/unvoicedsoundseparation/mir-1k) ([ckpt](https://storage.googleapis.com/ddsp-inv/ckpts/mir1k_ckpt.zip)).

MIR1k is actually a singing dataset, so you might find the best luck with that. Good luck!

**Comment by james20141606** [comment]
Thanks for the reply! I have already tried these three pretrained models! For two of my dataset, all the three models gave me better results! But for one particular dataset it seems the result is not very satisfying. some of the f0 could not be captured.

![image](https://user-images.githubusercontent.com/14315324/90680291-a18e0180-e22f-11ea-972e-69dc6c86c7a2.png)

I will train it with longer time to see if it could be better. The interesting thing is MIR1k model performs relatively worse than the other two. But I don't know why.
