### ISSUE TITLE
Pretraining with or without SpectralLoss?

### ISSUE THREAD

**Issue by faniuy** [magenta/ddsp#200]
In the file 'gin/papers/icml2020/pretrain_model.gin', the configurations are:

TranscribingAutoencoder.losses = [
     @losses.SpectralLoss(),
]
SpectralLoss.loss_type = 'L1'
SpectralLoss.mag_weight = 0.0
SpectralLoss.logmag_weight = 0.0

1. This configuration essentially disabled SpectralLoss by setting weights to zeros, but specified SpectralLoss in losses. So I'm a little confused.
2. This will cause Distrubuted ReduceOp problem in multi-gpu setting.

**Comment by jesseengel** [comment]
Hi! Thanks for the question. There are other losses for the synthetic data
(harmonic synth params, sinusoids) that are better signals for pretraining,
so the total loss is not 0.
