### ISSUE TITLE
'ValueError: need at least one array to concatenate' in train_autoencoder

### ISSUE THREAD

**Issue by turian** [magenta/ddsp#204]
In the train_autoencoder colab, depending upon what audio file I use, when running `colab_utils.save_dataset_statistics(data_provider, PICKLE_FILE_PATH)` I sometimes inexplicably get this error:

```
Calculating dataset statistics for <ddsp.training.data.TFRecordProvider object at 0x7f623fbf0d30>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-89c8bbab9ed7> in <module>()
      6 PICKLE_FILE_PATH = os.path.join(SAVE_DIR, 'dataset_statistics.pkl')
      7 
----> 8 colab_utils.save_dataset_statistics(data_provider, PICKLE_FILE_PATH)

1 frames
<__array_function__ internals> in vstack(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/shape_base.py in vstack(tup)
    281     if not isinstance(arrs, list):
    282         arrs = [arrs]
--> 283     return _nx.concatenate(arrs, 0)
    284 
    285 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```

How do I avoid this error? What types of input will trigger it? It appears like files under some length don't work.

Training will still go on even with PICKLE_FILE_PATH dataset_statistics.pkl being written. Is this file necessary? What happens if we ignore and don't generate it?

**Comment by JCBrouwer** [comment]
I ran into a similar error, although my training would not start without fixing it, so perhaps your case is slightly different.

For me, the cause of this were the files not corresponding to the default settings that are specified (at least 4 seconds @ 16 kHz). This causes errors in beam that just silently fail and continue. To fix it I had to remove all samples that were less than 4 seconds and ensure that all samples were 16 kHz.
