### ISSUE TITLE
Few bugs in code and readme

### ISSUE THREAD

**Issue by lukewys** [magenta/ddsp#218]
Hi all, thanks very much for your fabulous code and project. I tried to play with DDSP on my own and tried to run the solo_instrument training. Here are some bugs I found. I noticed that the code is under construction, so maybe the problems are planned to be solved in the near future or already solved.

1. Line 246 in spectral_ops.py: `int(n_secs * frame_rate)` will cause float point precision problem when having long audio as input. Simple test case: wav_length=2067968, sample_rate=16000, frame_rate=250. The correct result would be 2067968/16000*250=32312, but in python, the result would be 32311.999999999996, casting it to int will return 32311.
My solution here is to change it to `expected_len = int(round(n_secs * frame_rate))`, although I am not sure this is the right way to do it.

2. The training command in https://github.com/magenta/ddsp/tree/master/ddsp/training#train-1:
`  --gin_param="TFRecordProvider.file_pattern='/path/to/dataset_name*.tfrecord'" \` should change to ` --gin_param="TFRecordProvider.file_pattern='/path/to/dataset_name.tfrecord*'" \`, as the naming of the tfrecord is `dataset_name.tfrecord.xxx-of-xxx'

3. Need to comment or delete lines 152-165 of https://github.com/magenta/ddsp/blob/master/ddsp/training/eval_util.py in order to get the sample of the solo_instrument works. The error here was that there does not exist `ddsp.synths.NoisySinusoidal` (yet).

Best regards.

**Comment by sevagh** [comment]
I encountered bug 2 and 3 here during the training step. Fixing them helped my training continue.

Did you figure out how to get actual samples/audio generated from the trained model? When I run `mode=eval` or `mode=sample`, I don't actually get any wav file outputs anywhere.

**Comment by sevagh** [comment]
Here's my code generate dataset, train, eval, and sample:
```
# dataset prep
python -m ddsp.training.data_preparation.ddsp_prepare_tfrecord \
	--input_audio_filepatterns=/home/sevagh/ddsp-chowning-clarinet/datasets/raw/*mp3 \
	--output_tfrecord_path=/home/sevagh/ddsp-chowning-clarinet/datasets/tfrecords/train.tfrecord \
	--num_shards=10 \
	--alsologtostderr

# training
python -m ddsp.training.ddsp_run \
  --mode=train \
  --alsologtostderr \
  --save_dir="/home/sevagh/ddsp-chowning-clarinet/clarinet-autoencoder-training/" \
  --gin_file=ddsp/training/gin/models/solo_instrument.gin \
  --gin_file=ddsp/training/gin/datasets/tfrecord.gin \
  --gin_param="TFRecordProvider.file_pattern='/home/sevagh/ddsp-chowning-clarinet/datasets/tfrecords/train.tfrecord*'" \
  --gin_param="batch_size=16" \
  --gin_param="train_util.train.num_steps=100000"

# evaluate
python -m ddsp.training.ddsp_run \
  --mode=eval \
  --alsologtostderr \
  --save_dir="/home/sevagh/ddsp-chowning-clarinet/clarinet-autoencoder-training/" \
  --gin_file=ddsp/training/gin/models/solo_instrument.gin \
  --gin_file=ddsp/training/gin/datasets/tfrecord.gin \
  --gin_file="/home/sevagh/ddsp-chowning-clarinet/clarinet-autoencoder-training/operative_config-0.gin" \
  --gin_param="TFRecordProvider.file_pattern='/home/sevagh/ddsp-chowning-clarinet/datasets/tfrecords/train.tfrecord*'" \
  --gin_param="batch_size=16"

# sample
python -m ddsp.training.ddsp_run \
  --mode=sample \
  --alsologtostderr \
  --save_dir="/home/sevagh/ddsp-chowning-clarinet/clarinet-autoencoder-training/" \
  --gin_file=ddsp/training/gin/models/solo_instrument.gin \
  --gin_file=ddsp/training/gin/datasets/tfrecord.gin \
  --gin_file="/home/sevagh/ddsp-chowning-clarinet/clarinet-autoencoder-training/operative_config-0.gin" \
  --gin_param="TFRecordProvider.file_pattern='/home/sevagh/ddsp-chowning-clarinet/datasets/tfrecords/train.tfrecord*'"
```

**Comment by sevagh** [comment]
Ah I think:
>FYI, Those eval and sample jobs will just add tensorboard summaries, which you can then inspect and listen to.
https://github.com/magenta/ddsp/issues/151

I think I need to do that with these files:
```
│   └── summaries
│       ├── eval
│       │   ├── events.out.tfevents.1604063901.localhost.localdomain.6254.200.v2
│       │   ├── events.out.tfevents.1604063979.localhost.localdomain.7005.200.v2
│       │   ├── events.out.tfevents.1604064091.localhost.localdomain.7754.200.v2
│       │   ├── events.out.tfevents.1604064104.localhost.localdomain.8402.200.v2
│       │   ├── events.out.tfevents.1604064446.localhost.localdomain.11988.200.v2
│       │   ├── events.out.tfevents.1604064514.localhost.localdomain.12881.200.v2
│       │   └── events.out.tfevents.1604065581.localhost.localdomain.14877.200.v2
│       └── train
│           ├── events.out.tfevents.1603976943.localhost.localdomain.17712.7858.v2
│           ├── events.out.tfevents.1603976990.localhost.localdomain.18041.7858.v2
│           ├── events.out.tfevents.1604012065.localhost.localdomain.59988.7912.v2
│           ├── events.out.tfevents.1604012101.localhost.localdomain.61069.7912.v2
│           └── events.out.tfevents.1604020959.localhost.localdomain.72329.7912.v2
```

**Comment by jesseengel** [comment]
Hi, that's correct, the `eval` and `sample` jobs only create summaries in
tensorboard. You can also load up a model in colab and call `model(batch)`
like in the tutorials.

Also, 2 and 3 should be taken care of in the eval refactor #244 that just
merged.

**Comment by lukewys** [comment]
Thanks Jesse! Will the first one listed be a problem?

Thanks again.

(I'm Yusong Wu.)

**Comment by sevagh** [comment]
Fwiw @jesseengel there is a small typo in the eval refactor:
```
sevagh:ddsp $ git diff ddsp/training/gin/eval/basic_f0_ld.gin
diff --git a/ddsp/training/gin/eval/basic_f0_ld.gin b/ddsp/training/gin/eval/basic_f0_ld.gin
index fae718c..06b0db4 100644
--- a/ddsp/training/gin/eval/basic_f0_ld.gin
+++ b/ddsp/training/gin/eval/basic_f0_ld.gin
@@ -3,5 +3,5 @@ evaluators = [
     @F0LdEvaluator
 ]

-evaluate.evaluator_classes = %evalautors
+evaluate.evaluator_classes = %evaluators
```

**Comment by jesseengel** [comment]
Yup, thanks for catching this, we put in the typo fix.
