### ISSUE TITLE
Modular Decomposition of Audio

### ISSUE THREAD

**Issue by molo32** [magenta/ddsp#227]
I am using timbre_transfer.ipynb in colab
when outputting the audio in the Resynthesize Audio cell
it only outputs the Resynthesized audio, but I want the other decompositions as shown on this page in the section
"Modular Decomposition of Audio"

How do I get for example the "reber remover" as indicated on this page?

https://storage.googleapis.com/ddsp/index.html

**Comment by jesseengel** [comment]
you should be able to find it in the dictionary under `outputs = model.get_controls(batch)`. You want the `signal` output of the different processors. So, for instance, if you want the audio without reverb, you should take it from the "add" processor right before the reverb. I believe it should be something like `audio = outputs['add']['signal']`.
