### ISSUE TITLE
can you train with voices?

### ISSUE THREAD

**Issue by molo32** [magenta/ddsp#234]
can you train with voices, to use your voice as a singer?
If you do not know any similar project for voices?

**Comment by jesseengel** [comment]
You can train with voices but the output won't contain language as such. The model would need to be trained with linguistic features, but that is currently not a part of the code. You might have some luck with repos based on the tacotron family of models.
All the best,
Jesse

**Comment by jamesliu** [comment]
May you clarify how to add/extend linguistic features on current ddsp architecture? Is DDSP suitable to be extended in singing voice synthesis? Thanks.

**Comment by jesseengel** [comment]
Hi James,

It would require writing your own custom data processing, data loading, and
model code, but you could extract things like phonemes, convert them to
input features, and then train a model using that additional conditioning.

Best,
Jesse
