### ISSUE TITLE
Oauth2client version issues

### ISSUE THREAD

**Issue by FamousRob** [magenta/ddsp#235]
Apologies if any of this sounds dumb as I am completely new to using GitHub scripts, but there appears to be an issue relating to the version of Oauth2client or Python used in this project.

I ran a test training audio successfully last week, but now I get an error every time I try to use the project.

Specifically while running this script:

`%tensorflow_version 2.x
!pip install -qU ddsp[data_preparation]

# Initialize global path for using google drive. 
DRIVE_DIR = ''`

I get this error every time, and the rest of the project doesn't work - presumably because of the reported incompatibility:

`ERROR: pydrive 1.3.1 has requirement oauth2client>=4.0.0, but you'll have oauth2client 3.0.0 which is incompatible.
ERROR: apache-beam 2.24.0 has requirement avro-python3!=1.9.2,<1.10.0,>=1.8.1; python_version >= "3.0", but you'll have avro-python3 1.10.0 which is incompatible.
ERROR: apache-beam 2.24.0 has requirement dill<0.3.2,>=0.3.1.1, but you'll have dill 0.3.2 which is incompatible.
ERROR: apache-beam 2.24.0 has requirement future<1.0.0,>=0.18.2, but you'll have future 0.16.0 which is incompatible.
ERROR: apache-beam 2.24.0 has requirement requests<3.0.0,>=2.24.0, but you'll have requests 2.23.0 which is incompatible.`

I've tried it on multiple machines and it seems like the issue is related to the actual project rather than my machine.

If it's not a project issue but one on my system - does anyone know how to fix it?!

Thanks

**Comment by jesseengel** [comment]
Hi, can you provide more info about how it's not working for you? I just ran the notebook fresh and it seemed to work fine all the way through training and download. The import error messages are not fatal to training, but there may be some other issues at play.
