### ISSUE TITLE
error uploading audio to timbre_transfer

### ISSUE THREAD

**Issue by molo32** [magenta/ddsp#247]
error uploading audio to timbre_transfer

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-30190e9bd204> in <module>()
     28 # Compute features.
     29 start_time = time.time()
---> 30 audio_features = ddsp.training.metrics.compute_audio_features(audio)
     31 audio_features['loudness_db'] = audio_features['loudness_db'].astype(np.float32)
     32 audio_features_mod = None

5 frames
/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

ValueError: negative dimensions are not allowed
```

**Comment by bhaveshsingh0206** [comment]
I'm getting the same error. Idk what the problem is, this wasn't the issue before

**Comment by bhaveshsingh0206** [comment]
I tried with various audio files but still it is throwing the same error again and again.
<img width="864" alt="Screenshot 2020-11-02 at 2 34 53 PM" src="https://user-images.githubusercontent.com/44025948/97849433-93bd2800-1d18-11eb-9882-24a8a2e5dd75.png">

**Comment by bhaveshsingh0206** [comment]
@jesseengel Really need your help to get through this.

**Comment by bhaveshsingh0206** [comment]
@molo32 did u find a solution?

**Comment by molo32** [comment]
It seems that ddsp was updated to version '0.14.0'.
I solved them by installing an older version with

```
! pip uninstall ddsp
! pip install ddsp == '0.13.0'
```

**Comment by bhaveshsingh0206** [comment]
can u share your code @molo32

**Comment by bhaveshsingh0206** [comment]
ur entire colab notebook

**Comment by bhaveshsingh0206** [comment]
i'm still facing the same issue @molo32 and @jesseengel , also the song which gets upload now is quite very fast

**Comment by jesseengel** [comment]
Hmm, interesting, it might be related to the eval refactor, I'll have Rigel take a look

**Comment by jesseengel** [comment]
fwiw, I tried just now and wasn't able to reproduce the error with the colab notebook. I tried recording and uploading a .wav file and both seemed to work fine. Can you link an audio file that causes the error?

**Comment by ixje** [comment]
I hope you don't mind me "hijacking" the thread a bit. Using the attached file I get
```
Extracting audio features...
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-10-a4df020e4eeb> in <module>()
     19 
     20 # Plot.
---> 21 specplot(audio)
     22 play(audio)
     23 

11 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Can not squeeze dim[2], expected a dimension of 1, got 435096 [Op:Squeeze]
```

I tried different files and get the same error
[file_example_MP3_700KB.mp3.zip](https://github.com/magenta/ddsp/files/5826171/file_example_MP3_700KB.mp3.zip)

**Comment by ixje** [comment]
so it turns out when uploading a file `audio` is wrapped in an extra list. 
replace 
```python
  filenames, audios = upload()
  audio = audios[0]
```

with 

```python
  filenames, audios = upload()
  audio = audios[0][0]
```
to solve file upload usage. Recording with microphone worked fine

**Comment by mekriti** [comment]
@jesseengel , I'd like to contribute a few audio samples for magenta.js and other demoes.
Do you have a specific list/types the team might be looking for?
Thanks in advance and love the work the team is doing.

**Comment by svjetlonosha141** [comment]
Is anyone else still having this same issue? Even after changing the audios to [0][0] I keep getting errors when trying to play with timber-transfer and my pre-recorded sounds...
Any other ideas about what could be causing this? 

Thanks a lot, and excellent work altogether, this is just incredible! :)
