### ISSUE TITLE
Real time audio

### ISSUE THREAD

**Issue by pmusgrave** [magenta/ddsp#249]
Hi,

Really interesting library! I just found out about this and still reading through everything, so I'm sorry if this has been answered somewhere already. What's the status for real-time audio? Is the latency low enough to use this with a trained model on a real-time audio stream? Thanks!

**Comment by jesseengel** [comment]
Hi Paul,

It seems to be, we have an ongoing project to make VST plugins to do this
that's making progress. We'll open source all the code when it's ready.

Best,
Jesse

**Comment by pmusgrave** [comment]
Great, thanks! I'll keep an eye out for that. I'd be interested in contributing if that project needs any help.
