### ISSUE TITLE
Significant audio quality drop (timbre_transfer notebook) in 0.14.0

### ISSUE THREAD

**Issue by jesseengel** [magenta/ddsp#253]
The recent push to 0.14.0 includes a change that seems to have messed with the performance of the pretrained models. Unfortunately, there were a lot of commits in that version push, so I'm not exactly sure what the cause is yet, but I suspect it may be something regarding loading the checkpoints improperly. 

I'm looking into this right now, but for now, if you want to avoid this I recommend installing version 0.13.0, and I will make that the default for the notebook for now.
`!pip install ddsp==0.13.0`

**Comment by jesseengel** [comment]
Okay, an update, I think the culprit was #233 . I've since retrained models so the colab should be working again. Rather than revert at the moment, there are a couple breaking changes we've been waiting for a while to make, so I'm going to go ahead and push them through in the next week or so and update to v1. That means that models trained earlier will have to use v0.13.0 to run, but I think it's worth it in the long run.

I'm mark the versioning to make this clear.

**Comment by jesseengel** [comment]
Okay, so finally we've completed a pretty big refactor to take the code base up to v1.0.0 in #303. The colab notebooks are now pointing to newly trained models at HEAD.

**Comment by lauraibnz** [comment]
Hello, I have tried to switch to v1.0.0 and have changed the necessary class names in the gin files from older models (trained on v0.13.0). This way the models are loaded correctly but the resynthesized audio sounds worse in quality than it did with the previous version. An example:
[input_audio](https://drive.google.com/file/d/1vO21VjN7YMEGvWLQg-nvr1gWq4reevef/view?usp=sharing)
[resynthesized_old](https://drive.google.com/file/d/15bYtLnwgNUzz5HZOn5_96aEm4yAJbcMH/view?usp=sharing)
[resynthesized_new](https://drive.google.com/file/d/11hR_MuG7Hv00m0Aa5xAlaMSJbhfXbjcD/view?usp=sharing)
Could this have something to do with the latest changes in the decoder? I checked `f0_scaled` and `ld_scaled` in both cases and they were the same, it was `amps`, `harmonic_distribution` and `noise_magnitudes` which were already different.

**Comment by lauraibnz** [comment]
Update: switching to the previous nn functions used by the RnnFcDecoder the output `amps`, `harmonic_distribution` and `noise_magnitudes` are the same as when using the old version. The output signal of the Additive synth is also the same but the output signal of the FilteredNoise noise is still different. Any idea of why this can be?

**Comment by lauraibnz** [comment]
I checked further and the FiltereNoise output signal was actually fine, but the Reverb was acting differently (something to do with the latest changes in the dags?), outputting a very low signal. Finally using a copy of the old RnnFcDecoder with the old nn functions and a copy of the old ProcessorGroup (even using the new synths and effects) made it possible to use the old models as before. Still haven't figured out why this is happening though.

**Comment by jesseengel** [comment]
Sorry you had the trouble. I believe the DAGLayer was having trouble
claiming the variables of its sub components. Looks like it came from using
`__dict__[]` instead of `setattr()` to create modules in DAGLayer, which
was skipping `__setattr__` where variable inheritance occurs, so the
processor_group variables weren't collecting the IR variable from Reverb.

As ddsp.training is actively used for research purposes, we unfortunately
don't have the bandwidth to support complete backwards compatibility, but
hopefully versions before 1.0 should work for old models and training new
models with 1.0 should still work.
