### ISSUE TITLE
Documentation request: how to use a custom .gin file with `ddsp_run`?

### ISSUE THREAD

**Issue by nielsrolf** [magenta/ddsp#257]
In the train_autoencoder.ipynb, the `ddsp_run` call looks like this:
```
!ddsp_run \
  --mode=train \
  --alsologtostderr \
  --save_dir="$SAVE_DIR" \
  --gin_file=models/solo_instrument.gin \
  --gin_file=datasets/tfrecord.gin \
  --gin_param="TFRecordProvider.file_pattern='$TRAIN_TFRECORD_FILEPATTERN'" \
  --gin_param="batch_size=16" \
  --gin_param="train_util.train.num_steps=30000" \
  --gin_param="train_util.train.steps_per_save=300" \
  --gin_param="trainers.Trainer.checkpoints_to_keep=10"
```

It is unclear to me where the gin files are loaded from since the paths `models/solo_instrument.gin` and `datasets/tfrecord.gin` don't exist in the file system of the runtime. It would be great if someone can explain how the gin files are loaded, and how to a custom file.

**Comment by nielsrolf** [comment]
The error message if you change the path gives the answer: `OSError: Unable to open file: models/solo_instrument123.gin. Searched config paths: ['', '/usr/local/lib/python3.6/dist-packages/ddsp/training/gin'].`

**Comment by jesseengel** [comment]
Glad it worked out for you. You can also configure a custom directory to
search within with the flag --gin_search_path

flags
<https://source.corp.google.com/piper///depot/google3/third_party/py/absl/flags/__init__.py;rcl=341155201;l=0>
.DEFINE_multi_string
<https://source.corp.google.com/piper///depot/google3/third_party/py/absl/flags/__init__.py;rcl=341155201;l=69>
('gin_search_path', [],
'Additional gin file search paths.')
