### ISSUE TITLE
Broken colabs

### ISSUE THREAD

**Issue by seicaratteri** [magenta/ddsp#258]
Hello! First of all, thanks for the work - is incredible! 🥇 

I think the last updates introduced some errors in the colab notebook for timbre transfer. When training, extracting the dataset statistic does not work for me anymore, as shown here:

![err training](https://user-images.githubusercontent.com/3061306/98688308-fe024800-236a-11eb-860a-f17d4bfc6056.jpg)

Also, when using a trained model i get this error:

![immagine](https://user-images.githubusercontent.com/3061306/98688547-415cb680-236b-11eb-94a0-3ac2d61fbc93.png)

Do you know any quick soluton for this? I also tried using v0.13.0 and doesn't work! Should I rollback and use a colab notebook from the past? Thank you!

**Comment by jesseengel** [comment]
I found the problem was a dataset iterator in save_dataset_statistics() was using batch_size=128 and returning nothing if the dataset was smaller. I've fixed it by setting the batch_size=1 for now.
