### ISSUE TITLE
Real time capabilities

### ISSUE THREAD

**Issue by seicaratteri** [magenta/ddsp#261]
Hello!

Is there a way to get real-time timbre transfer from a trained model? I managed to train the tiny model and the inference even on CPU is super quick (fractions of seconds) but the huge bottleneck I'm experiencing is related to the feature extraction (loudness and f0). On CPU, for about 1s of audio it takes 8 seconds and for 23s it takes over 4minutes. Is there a way to reduce this computing time?

Thank you in advance and keep up the great work! :)

**Comment by jesseengel** [comment]
Hi, I believe you're probably seeing most of the slowdown in the inferring of f0 with CREPE, and in the loading of models. We've been able to get models running faster than realtime on CPU in TF.js (g.co/tonetransfer) (and TFLite for some VST plugins we're developing) so it's definitely possible. You have to run a batch to build/load the model at first, but it should run much faster the second time after the model is built. Hope that helps.

**Comment by seicaratteri** [comment]
Hi @jesseengel! Thank you very much, I appreciate your help! 🥇 

I also noticed that after the first run it would run faster but it is still way slower than realtime (8s processing for 1s audio). This happens both on my pc CPU and on colab CPU.

The way to go then would be to convert the CREPE model to tflite so that it could infer faster?

Thank you so much again! :)
