### ISSUE TITLE
'Autoencoder' object has no attribute 'get_audio_from_outputs' in colab/demos/timbre_transfer.ipynb

### ISSUE THREAD

**Issue by jamesliu** [magenta/ddsp#262]
I run timber_transfer.ipynb with the error below. Is it version issue? 
Thanks

AttributeError                            Traceback (most recent call last)
<ipython-input-130-f5b7158ef13e> in <module>()
      7 outputs = model(af, training=False)
      8 print(type(model))
----> 9 audio_gen = model._outputs(outputs)
     10 print('Prediction took %.1f seconds' % (time.time() - start_time))

AttributeError: 'Autoencoder' object has no attribute 'get_audio_from_outputs'

**Comment by jesseengel** [comment]
Hi,

Yah, I'm not sure when you tried the demo, but it should work fine now as
the version has been corrected.

**Comment by jamesliu** [comment]
@jesseengel  After updating ddsp, it is fixed. Thanks.
