### ISSUE TITLE
evaluation with distinct targets (not resynthesis of orginal audio)

### ISSUE THREAD

**Issue by lstrgar** [magenta/ddsp#266]
Hi! Wondering if in current state it is possible to evaluate a trained decoder against target audio that is not the original input audio? I have 10 singers, all singing the same collection of songs. I've trained a model to synthesize singer X's voice, now I want to, for a single song, extract features for the 9 remaining singers for input to the trained model and evaluate synthesized audio against singer X's recording of the same song. I presume the best way to do this (though not sure if this is possible or recommended) would be to create a data provider from the other 9 singer's collection of recordings plus computed features (e.g. ddsp_prepare_tfrecord) and then replace the audio in that data provider with the appropriate selection for singer X. Any easier methods come to mind? Thanks in advance for your thoughts. 

Luke

**Comment by jesseengel** [comment]
Sorry for the super long delay. That would be my recommendation for how to go about doing it, so hope it worked out okay for you.
