### ISSUE TITLE
timbre-transfer example -> If source sample is 'long', play(gen_audio) can not be downloaded via gui

### ISSUE THREAD

**Issue by salkin-mada** [magenta/ddsp#27]
I am often having problems with not being able to download the result from the small soundfile gui (the vertical three dots) in the [colab](https://colab.research.google.com/github/magenta/ddsp/blob/master/ddsp/colab/demos/timbre_transfer.ipynb) when files are long >45~ seconds. (using upload, and .wav - both with pretrained and custom checkpoint)

if using a small 13mb file (for an example) there is no problem the download button throws/opens a os window for downloading or it will just download to the sys/os download folder immediately, as download.wav  . depending on browser used and settings.

FYI, i have tried with chrome, firefox and brave. running debian buster.
and macOS mojave with firefox, chrome and safari.
sometimes i have the problem of not being able to download sometimes not.
tried to clear my cache and logout of google account + restarting runtime and refreshing page. no help. download button in soundfile view just results in "download failed due to network connection error" or even sometimes just nothing. no error, no os window pop up. 

and I have double checked that it is not my network connection which is the trouble maker or that is is something i am doing wrong on my system. So when i experience this bug i immediately go to another colab running (for an example) some librosa stuff or even another ddsp demo like one from the [tutorials](https://colab.research.google.com/github/magenta/ddsp/blob/master/ddsp/colab/tutorials/0_processor.ipynb) and there i can download results from processes. no problem.

I would love to write the resynthesis output from model(af, ...) to the files directory. but I am not able to find any write out or store funcs in the ddsp lib.

PS. ddsp is making so nice sounding material compared to other ML resynthesis methods i have come across. Good job. And many thanks for sharing.

**Comment by jesseengel** [comment]
Hi! Unfortunately this seems to be a generic problem for downloading large files from an html component (https://superuser.com/questions/1485591/cant-download-a-certain-large-file-error-failed-network-error). 

Two things that could help:
(1) As a workaround for now you can save the file to the local file system with `librosa.output.write_wav('audio_gen.wav', np.ravel(audio_gen), sr=16000)`, and then download the file with a right click on the file browser in the left panel.

(2) You will actually get higher audio quality with shorter samples. There's a known bug at the moment that float32 causes some error accumulation in the cumsum that is more audible past 10 seconds usually. So if you can cut your audio neatly into smaller chunks it should sound better.

**Comment by salkin-mada** [comment]
Thanks! Was not aware of the html component bug.
1) librosa to the rescue, great.
2) okay some sox magic or ffmpeg stuff will fix this easily
