### ISSUE TITLE
Preprocess raw audio into TFRecord dataset ERROR

### ISSUE THREAD

**Issue by eoinrussell** [magenta/ddsp#270]
Whatever filetype I use wav, mp3, 16 bit, 24 bit, mono, stereo, short, long.  I get this error and never get a TFRecord file returned to my Google Drive directory.  I've tried it without Drive as well and I still get the error.

RuntimeError: tensorflow.python.framework.errors_impl.FailedPreconditionError: data/audio/.ipynb_checkpoints; Is a directory [while running 'Map(_load_audio)']
mkdir: cannot create directory ‘/content/drive/MyDrive/AI02/data/’: File exists
Saving to /content/drive/MyDrive/AI02/data
cp: cannot stat 'data/train.tfrecord*': No such file or directory

Any ideas?

**Comment by ash11sh** [comment]
Colaboratory may throw memory errors if it encounters large single audio files—cut the file into smaller pieces

**Comment by bhaveshsingh0206** [comment]
Even i m getting the same error. @eoinrussell did u resolve it?

**Comment by bhaveshsingh0206** [comment]
@jesseengel Really need your help to get through this.

**Comment by bhaveshsingh0206** [comment]
@jesseengel Really need your help to get through this..
I m getting this again and again. @eoinrussell 
<img width="1440" alt="Screenshot 2020-12-03 at 5 33 44 PM" src="https://user-images.githubusercontent.com/44025948/101015623-b350a600-358d-11eb-9e82-f695a1af873e.png">

**Comment by eoinrussell** [comment]
Without changing anything on my end, I am now training against a 20 minute, uncompressed wav file.  So, I seem to have gotten past that step without doing anything new myself.  So hopefully, whatever was causing the issue has been adjusted.

**Comment by zqevans** [comment]
I'm still getting this. Has anyone else figure out how to fix it other than waiting for it to fix itself?

**Comment by jesseengel** [comment]
Can you link to a wav file that is reliably causing this error when you try
to train?

**Comment by chariells** [comment]
> I'm still getting this. Has anyone else figure out how to fix it other than waiting for it to fix itself?
> 
> Edit: The issue was passing in too large of audio files. I cut down the amount of audio I was passing in and now training works

Would you happen to know the threshold in seconds? It would be good to know the max. Definitely, something that should be indicated plainly if it's a hard stop for the system. Thanks for sharing!

**Comment by eoinrussell** [comment]
I was able to train against a 20 minute mono WAV file. 160MB or so. It seems that when I get this error, if I leave it for a day and try again, it works.  I know waiting a day isn't particularly helpful...  but that's what worked for me.

**Comment by mlaugharn** [comment]
Had this issue happen to me also
