### ISSUE TITLE
SavedModel conversion

### ISSUE THREAD

**Issue by ash11sh** [magenta/ddsp#274]
how to convert checkpoints to saved models

**Comment by TardisOnMars** [comment]
Hi ! We're also interested in this feature, in order to run the DDSP model with the C/C++ API.
I guess in order to convert the checkpoint files to a SavedModel, you would need to create a model (e.g. ddsp.training.models.Autoencoder()), load its weights and then call model.save().

However, when calling 'model.save()' on the Timbre Transfer demo (after the "Load a Model" section) on Google Collab, I get this error : 

```
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 80, 1000, -1]. Consider casting elements to a supported type.
  In call to configurable 'angular_cumsum' (<function angular_cumsum at 0x7f15786a8ae8>)
  In call to configurable 'oscillator_bank' (<function oscillator_bank at 0x7f15786a8bf8>)
```

Hope we can find a solution :)

**Comment by jesseengel** [comment]
Hi, we use SavedModel conversion for both our [TF.js models](
https://github.com/magenta/magenta-js/tree/master/music/src/ddsp) and our
upcoming TFLite JUCE plugins that aren't open sourced yet. I'll hopefully
open source the model conversion script this week, it uses the wrappers in
ddsp/training/inference.py

**Comment by linareyne** [comment]
Any update on this? And are the TFlite juce plugins planned to be open sourced?

**Comment by jesseengel** [comment]
Yup, we got a prototype working just before the break so we hope to release
a basic version early this year. We’ll also open source the scripts so you
can reproduce the full pipeline.

**Comment by nilsdnz** [comment]
@jesseengel Any chance you've already open sourced the conversion scripts? Are there any resources or code snippets available regarding this issue?

**Comment by jesseengel** [comment]
Hi, sorry, we're still waiting on a bug fix deep within tensorflow to
unblock it but hopefully it shouldn't be tooo much longer. I'll give them
another ping.

**Comment by InspiringPeople** [comment]
@jesseengel Do you have any updates? Thanks in advance

**Comment by jesseengel** [comment]
You should be able to use the `ddsp_export` script: https://github.com/magenta/ddsp/blob/main/ddsp/training/ddsp_export.py

Usage instructions are in the doc string. It is still under active development hasn't been thoroughly tested for exporting tfjs, but should work for SavedModel and TFLite.
