### ISSUE TITLE
Problem when using the colab demo

### ISSUE THREAD

**Issue by Aozhi** [magenta/ddsp#279]
Hi, 

Thank you so much for this awesome work. I am trying to uploda my audio to do timbre transfer in your model . However, when I implemented the colab demo and run the cell called 'Load a model', I got this message: No configurable matching 'F0LoudnessPreprocessor'. Should I do any modificaiton to treat this problem? Thank you so much!

**Comment by jesseengel** [comment]
Thanks for catching this, fix will be in shortly.

**Comment by VegetaDTX** [comment]
I was literally trying to post the same issue just 5 mins ago :) I'm looking forward to the fix!
