### ISSUE TITLE
Fixed-duration with output audio when training with own dataset

### ISSUE THREAD

**Issue by DragonDisco** [magenta/ddsp#315]
Thank you for you awsome work. I attempted to reproduce the training process with my own dataset, which contains audios with 4-second durations. However, when I tried to resynthesizes the audio, the reconstructed audio can only be in 4 seconds.  May I ask that what's wrong with my training process? Thank you and looking for your reply.

**Comment by jesseengel** [comment]
Sorry for the delayed response. We only support fixed-length inputs / outputs for a given instantiation of a model at the moment. You can get around this by rebuilding a model for different resynthesis sizes, which you can see how we do it in the timbre_transfer.ipynb notebook.
