### ISSUE TITLE
Alternative of uploading a song.

### ISSUE THREAD

**Issue by bhaveshsingh0206** [magenta/ddsp#319]
@jesseengel Is there any way that instead of uploading a song i can directly use a song from drive or anywhere in timbre_transfer?

**Comment by jesseengel** [comment]
Sure thing, if you look at the train autoencoder notebook you'll see an
example of how to load files from drive into colab. You could then modify
the timbre_transfer notebook to do the same.

**Comment by bhaveshsingh0206** [comment]
@jesseengel I'm not able to understand how that thing can be used in timbre_transfer. I think both are doing different things. It will be nice if you can help.

**Comment by bhaveshsingh0206** [comment]
Like how do make use of this func audio_bytes_to_np, which is getting used in upload() func. @jesseengel

**Comment by bhaveshsingh0206** [comment]
@jesseengel can you help on this matter?

**Comment by bhaveshsingh0206** [comment]
I keep on getting this error. @jesseengel 
![Uploading Screenshot 2021-02-13 at 11.59.33 PM.png…]()

**Comment by bhaveshsingh0206** [comment]
I keep on getting this error..
<img width="1122" alt="Screenshot 2021-02-13 at 11 59 33 PM" src="https://user-images.githubusercontent.com/44025948/107857981-bd2d3a00-6e57-11eb-8df0-a026b2a9fb45.png">

**Comment by jesseengel** [comment]
Sorry for the delay, it seems like a problem with the ffmpeg backend that pydub uses in `audio_bytes_to_np()`. From the colab, it seems to work fine for `.wav` and `.mp3` files, but maybe you're using a different file type? Also you want to make sure to read the bytes from disk rather than passing in the filename.
