### ISSUE TITLE
timbre_transfer error uploading mp3 (Can not squeeze dim[2])

### ISSUE THREAD

**Issue by Hunterwolf88** [magenta/ddsp#323]
Hello,
I trained my model on my local machine with my dataset, now I'm trying Colab "timbre_transfer" demo since I'm new and I'm not sure how to do the same on my computer.

When I upload the mp3 I want to use I get this error:

`InvalidArgumentError: Can not squeeze dim[2], expected a dimension of 1, got 7164672 [Op:Squeeze]`

The file is just an mp3, 320kBps. The duration is about 7 minutes.
Is it too long or something or is it a bug?
I also get some errors while installing the pip packages in the Colab, not sure if related:
```
ERROR: pynndescent 0.5.1 has requirement numba>=0.51.2, but you'll have numba 0.49.1 which is incompatible.
ERROR: note-seq 0.0.2 has requirement numba==0.48.0, but you'll have numba 0.49.1 which is incompatible.
```

If someone can also teach me a script to run the timbre_transfer on my local machine it would be amazing <3

**Comment by Hunterwolf88** [comment]
Tried:
- uploading wav files
- shorter ones
- shorter record_seconds (probably this isn't correlated at all)
- using numba>=0.51.2

Same error everytime

**Comment by Hunterwolf88** [comment]
I was able to fix using `audio = audios[0][0]` instead of   `audio = audios[0]`.
Could it be that my files were all stereo?

If this is the case maybe we want to add something like a selector.

**Comment by jesseengel** [comment]
Sorry about the delay in replying. Do you have the audio file that caused it? I suspect it is because it's stereo, and averaging would the two or selecting one of them would be a good option.

**Comment by jesseengel** [comment]
Finally getting around to this (enough folks were complaining on twitter), it seems it is due to the stereo option, and I'm putting a fix in.
