### ISSUE TITLE
timbre_transfer colab with my model: ResourceExhaustedError: OOM

### ISSUE THREAD

**Issue by Hunterwolf88** [magenta/ddsp#324]
Hello there,

I'm using Colab "timbre_transfer" to test the model I trained with my own audio.
I trained the model on my local machine but I'm not able to run the timbre transfer on it (any help?)

Anyway, using my own model in Colab I get this error:

```
ResourceExhaustedError: OOM when allocating tensor with shape[1,60,111949,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Mul]
  In call to configurable 'run_dag' (<function DAGLayer.run_dag at 0x7f23e891ec80>)
```

What's the best way to avoid going out of memory?
Using the hosted GPU runtime. I have an 11GB GTX 1080Ti but, again, I wasn't able to run the timbre transfer on my local machine without a guide.

big thanks to anyone who can help me!

**Comment by Hunterwolf88** [comment]
after some testing it seems to me that it is because of the length of the audio file, not the model.

**Comment by jesseengel** [comment]
Sorry it took so long to respond, but looks like you figured it out. Yah the functions don't chop up large audio segments automatically so they need to be kept below memory limits manually. Thanks!
