### ISSUE TITLE
How to deal with variable-length sequences?

### ISSUE THREAD

**Issue by xdurch0** [magenta/ddsp#33]
Hey,

I'm struggling with getting a simple (e.g. additive) synth to run with variable length data. Say, you are trying to train an autoencoder but the data is not always exactly the same length. 

- Problem 1: The synth already needs `n_samples` at initialization. Why is this? It makes much more sense to me to have this argument when _calling_ the synth.
- Problem 2: In principle, I don't mind creating a new synth object every time I want to use it (i.e. decode), since the initialization seems fairly trivial (shouldn't produce much overhead... right?). So I could just do that and always pass in the `n_samples` I need _at that time step_. However, I'm not sure what the correct way of doing this would be. I tried passing a tensor shape as `n_samples`, but this leads to a crash, see below.

Short code example:

```python
def test(inp):
    # inp is a dummy -- it just represents "something with variable length"
    osc = ddsp.synths.Additive(n_samples=int(tf.shape(inp)[0]))
    # dummy values for amplitude/harmonics/f0
    audio = osc([[[3.], [2.], [5.]]], [[[3.], [2.], [5.]]], [[[441.], [442.], [443.]]])
    return audio

test(tf.random.normal([102]))
```

This leads to the following crash

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-5d43e4898acc> in <module>
----> 1 test(tf.random.normal([102]))

<ipython-input-78-211339ba06f2> in test(inp)
      1 def test(inp):
      2     osc = ddsp.synths.Additive(n_samples=tf.shape(inp)[0])
----> 3     audio = osc([[[3.], [2.], [5.]]], [[[3.], [2.], [5.]]], [[[441.], [442.], [443.]]])
      4     return audio

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

/usr/local/lib/python3.6/dist-packages/ddsp/processors.py in call(self, *args, **kwargs)
     59     """Convert input tensors arguments into a signal tensor."""
     60     controls = self.get_controls(*args, **kwargs)
---> 61     signal = self.get_signal(**controls)
     62     return signal
     63 

/usr/local/lib/python3.6/dist-packages/ddsp/synths.py in get_signal(self, amplitudes, harmonic_distribution, f0_hz)
     97         harmonic_distribution=harmonic_distribution,
     98         n_samples=self.n_samples,
---> 99         sample_rate=self.sample_rate)
    100     return signal
    101 

/usr/local/lib/python3.6/dist-packages/ddsp/core.py in harmonic_synthesis(frequencies, amplitudes, harmonic_shifts, harmonic_distribution, n_samples, sample_rate, amp_resample_method)
    405   frequency_envelopes = resample(harmonic_frequencies, n_samples)  # cycles/sec
    406   amplitude_envelopes = resample(harmonic_amplitudes, n_samples,
--> 407                                  method=amp_resample_method)
    408 
    409   # Synthesize from harmonics [batch_size, n_samples].

/usr/local/lib/python3.6/dist-packages/ddsp/core.py in resample(inputs, n_timesteps, method, add_endpoint)
    124 
    125   elif method == 'window':
--> 126     outputs = upsample_with_windows(inputs, n_timesteps, add_endpoint)
    127 
    128   else:

/usr/local/lib/python3.6/dist-packages/ddsp/core.py in upsample_with_windows(inputs, n_timesteps, add_endpoint)
    170                          n_frames, n_timesteps))
    171 
--> 172   if n_timesteps % n_intervals != 0.0:
    173     minus_one = '' if add_endpoint else ' - 1'
    174     raise ValueError(

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py in tensor_not_equals(self, other)
   1363   if ops.Tensor._USE_EQUALITY and ops.executing_eagerly_outside_functions():
   1364     if fwd_compat.forward_compatible(2019, 9, 25):
-> 1365       return gen_math_ops.not_equal(self, other, incompatible_shape_error=False)
   1366     else:
   1367       return gen_math_ops.not_equal(self, other)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_math_ops.py in not_equal(x, y, incompatible_shape_error, name)
   6435         _ctx._context_handle, tld.device_name, "NotEqual", name,
   6436         tld.op_callbacks, x, y, "incompatible_shape_error",
-> 6437         incompatible_shape_error)
   6438       return _result
   6439     except _core._FallbackException:

TypeError: Cannot convert 0.0 to EagerTensor of dtype int32
```

which I assume is due to `n_timesteps` being a tensor in `upsample_with_windows`. In this case it can be fixed by converting the shape to an `int()` explicitly, but this won't work when using `@tf.function` because the shape is not known at the time the code is actually run. Any workarounds? My colleague proposed simply initializing one synth for every possible length and choosing the correct one on the fly, but this seems wasteful.

I hope this is the right place to ask this. All the tutorials seem to be using fixed-length data (e.g. always 4 seconds) but I don't think variable lengths are a particularly exotic scenario.

**Comment by jesseengel** [comment]
Hi Jens,

I agree that the current setup could be improved. As you've said, the current setup assumes a fixed length at construction and then cuts and pads the input data into fixed-length chunks. We then take a pretrained model and change the length when we rebuild for inference to a different length. 

The only reason we need to specify the length at all is because most of these ops have an upsampling step to get from network outputs to audio rate. But I _think_ there's nothing stopping this from being an input argument, I'll look into it further.

For now, your workaround (construct the processors each time) should be fine and about as lightweight as just calling the functions themselves. The only exception is the Reverb processors which actually have parameters if `trainable=True`, so would need to be treated more like neural net layers.

As far as your error, you probably want to make sure you're using the latest TF. I tried your example in [this colab notebook](https://colab.research.google.com/drive/1vW0Qjgfh-fZL18x7-_uDI51-egaYUxYa) and it seems to work for both eager mode and with @tf.function. (you also need to use `tensor.shape[0]`).

That should handle your case for now, but please let me know if you hit any more snags, and I'll take a look at this function call idea when I get a free moment.

**Comment by xdurch0** [comment]
Dear Jesse,

thank you for your swift response. The main reason  I was wondering about the samples-at-init thing is that the classes I looked at (e.g. additive or wavetable synth) don't actually do anything with this parameter in `__init__` except for saving it as an attribute, so it would seem straightforward to simply pass this to `call` instead. However, I did not consider cases such as trainable Reverb, so it might not be as simple in the general case. Another option (I think I would have coded it this way) would be to have a fixed upsampling factor from frames to samples. That way the output length could be dynamically determined based on input length (number of frames). But I guess this would come with a loss of flexibility wrt the upsampling procedure...

As for the error, I am using the newest TF version. Your fix does work because `Tensor.shape` returns a list of ints instead of a `TensorShape`. However, this is just because the input length is known/fixed. In the general case, I would have something like this:

`test = tf.function(test, input_signature=(tf.TensorSpec(shape=[None]),))`

Since we need to accommodate different lengths, the "expected" shape should be `None`, which gives the error

```
ValueError: in converted code:

    <ipython-input-97-5530be6399a6>:3 test  *
        audio = osc([[[3.], [2.], [5.]]], [[[3.], [2.], [5.]]], [[[441.], [442.], [443.]]])
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py:822 __call__
        outputs = self.call(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/ddsp/processors.py:61 call
        signal = self.get_signal(**controls)
    /usr/local/lib/python3.6/dist-packages/ddsp/synths.py:99 get_signal
        sample_rate=self.sample_rate)
    /usr/local/lib/python3.6/dist-packages/ddsp/core.py:405 harmonic_synthesis
        frequency_envelopes = resample(harmonic_frequencies, n_samples)  # cycles/sec
    /usr/local/lib/python3.6/dist-packages/ddsp/core.py:122 resample
        align_corners=not add_endpoint)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py:1225 resize_images
        skip_resize_if_same=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/image_ops_impl.py:1086 _resize_images_common
        raise ValueError('\'size\' must be a 1-D int32 Tensor')

    ValueError: 'size' must be a 1-D int32 Tensor
```

Also, my colleague's fix doesn't actually work (inside the function decorator) because there would need to be some way to pick the correct synth out of all the different options (one for each possible `n_samples`) and I am not aware of any structure in TF that allows for indexing with tensors that are unknown at compile time (in this case, the unknown input length). The only thing would be `TensorArray`, but this can only store tensors, not synths... but I digress.

For now, I will leave out `tf.function` and work in eager mode instead, since this allows for creating synths "on demand" as the input lengths can be accessed directly. For our current application it would also not be all that dramatic to work on fixed-length slices. I was just wondering if I was missing something. :) Thanks for the library, I think DDSP is a great approach, and I look forward to "taking it apart" in the future!

**Comment by jesseengel** [comment]
Hi Jens,

That's right, you'll need to explicitly specify the length of each batch, because tf.image.resize needs to know the actual values, not just the relative increase I believe. I think you should be able to just perform some part of the data loading in eager so you can make sure each batch has an actual shape before you pass it to the tf.function.

Just to clarify, you don't need a container of precompiled functions. Wrapping `test` with @tf.function will lazily recompile only for each new length I believe. This will incur a cost of recompiling a graph for every new shape you pass it, so if you have _lots_ of different lengths during training, at some point eager may be faster, depending on the ratio of different numbers of lengths to total training steps. But for a long training, I think graph would always win out.

**Comment by xdurch0** [comment]
Hey,

you're right, what I was thinking of would be closer to something like an Upsampling1D layer...

Unfortunately, we do have "lots" of different lengths since the scenario is working on "semantic" units, say each sequence is a sentence recording, and so there is a large range of possible input lengths with most if not all possibilities inbetween also being represented. Either way, turns out eager execution is definitely fast enough right now,  so it works fine (except for going OOM on long sequences -- but that's a different story and most likely due to our architecture). If you want to close this issue for now, I'd be fine with that.

**Comment by jesseengel** [comment]
Thanks, good luck!

**Comment by voodoohop** [comment]
@jesseengel Is there anything that would prohibit setting the RNN nodes to `stateful=true` and processing the audio in batches of e.g. 2048 samples?

**Comment by jesseengel** [comment]
I think if you are training with variable length sequences, and using tf.function to JIT the graph, you still would need to compile all the different length graphs as they come (even if stateful=true, which would just help with passing state forward from batch to batch, but deal with the compilation of different sizes of the graph).

**Comment by voodoohop** [comment]
@jesseengel I'm not planning to train on variable-length sequences. I'd still continue training on e.g. 4 second sequences.

At inference time I would simply build the model using a fixed size of e.g. 2000 samples and set `stateful=true`. Then the long audio to process would be cut into chunks of 2000 samples and the last part zero-padded before feeding it chunk by chunk into the model.

If we run the whole process through the DDSP synths I would imagine the windowing functions could cause clicks at the edges. Maybe one would have to calculate with some overlap or something.

Am I making some fundamental mistake?

**Comment by jesseengel** [comment]
Ah, no, sorry misunderstood. That makes sense. Fwiw, we've done such stitching before and the edge effects (even with a 0 initial state for the RNN each chunk, haven't been noticeable. Especially if you do overlapping chunks with a short fade between. 

There is an implicit state as well in the phase of the additive oscillators that will create a phase discontinuity at the chunk boundaries, but ddsp uses windows for synsthesis so that helps smooth it out too. Good luck!
