### ISSUE TITLE
is it possible to provide the audio sample used in ICLR paper

### ISSUE THREAD

**Issue by james20141606** [magenta/ddsp#34]
It's truly amazing work and thanks for the codes! I'd like to reproduce the auto-encoder demo model you described in the paper. Can I find the violin audio sample in some places?

**Comment by jesseengel** [comment]
The violin model in the demo colab is the same one released in the paper. You should be able to get the same reconstructions if you use audio from the same dataset. They were the violin recordings of John Garner on MusOpen. I can't direct link for some reason but you can find them with a search here: https://musopen.org/music/
