### ISSUE TITLE
1.6.1 isn't in pip version list

### ISSUE THREAD

**Issue by puffywastaken** [magenta/ddsp#378]
I don't know if this was a mistake, but no one has updated the ddsp data prep library to 1.6.1

Thank you!

**Comment by jamesb93** [comment]
I think you need to elaborate on the problem to help the maintainers. In the DDSP colab notebooks pip is pinned to version 1.6.1 which fails:

https://colab.research.google.com/github/magenta/ddsp/blob/master/ddsp/colab/demos/train_autoencoder.ipynb#scrollTo=Bp_c8P0xApY6

**Comment by jesseengel** [comment]
Hi James, thank you that was very helpful. I'm about to update the pip package which should handle that. Thanks!
