### ISSUE TITLE
Input dimension errors when using multiple GPUs (tutorial 3_training)

### ISSUE THREAD

**Issue by sevenfx** [magenta/ddsp#49]
Hello.  I've been working through the tutorials, running them locally on my machine.  When running with a single GPU, I was able to get the `3_training.ipynb` running just fine after adding in 
```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```

When I have my second GPU enabled as well:
```
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
```

I get an error on this line: `trainer.build(next(iter(dataset)))`:

```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input dimension 2 must have length of at least 256 but got: 64
	 [[node replica_1/autoencoder/processor_group/rfft (defined at /site-packages/ddsp/core.py:683) ]]
  (1) Invalid argument:  Input dimension 2 must have length of at least 256 but got: 64
	 [[node replica_1/autoencoder/processor_group/rfft (defined at /site-packages/ddsp/core.py:683) ]]
	 [[replica_1/autoencoder/processor_group/add_4/_10]]
0 successful operations.
0 derived errors ignored. [Op:__inference___call___11281]

Errors may have originated from an input operation.
Input Source operations connected to node replica_1/autoencoder/processor_group/rfft:
 replica_1/autoencoder/processor_group/frame/Reshape_4 (defined at /site-packages/ddsp/core.py:670)

Input Source operations connected to node replica_1/autoencoder/processor_group/rfft:
 replica_1/autoencoder/processor_group/frame/Reshape_4 (defined at /site-packages/ddsp/core.py:670)

Function call stack:
__call__ -> __call__
```

I'm running with two 2070 Supers, and I don't fully understand the whole `allow_growth` thing either, but I'm wondering if you may have any idea why I'm able to run on a single GPU but not both.  Let me know if I can provide any more information.  Thanks in advance for the help, and thanks for the awesome library!

**Comment by jesseengel** [comment]
The memory growth issue should be fixed with #42 (I believe it's because your GPUs have less memory). 

3_training.ipynb is only set up to train on a single example and I've only tested it using the built-in colab gpu. Are you increasing the batch size so that it can be split between the two gpus?

**Comment by sevenfx** [comment]
Ah, that was it.  Started working with as few as 2 in batch size.  Who would have thought two GPUs was overkill for training on a single example... Anyway thanks!

**Comment by sevenfx** [comment]
BTW - I had an issue when trying to generate the audio from the distributed dataset -- ended up having to convert the configs back to regular tensors as opposed to the `PerReplica` versions.  Will play around with it a little more though..

**Comment by jesseengel** [comment]
Glad it worked out for you, thanks for looking into this.
