### ISSUE TITLE
f0 in gansynth_subset is wrong

### ISSUE THREAD

**Issue by dhgrs** [magenta/ddsp#54]
The latest crepe(==0.0.10) has a bug on `crepe.predict` and ddsp uses it to calculate f0.
Related issue: https://github.com/marl/crepe/issues/49
Where used: https://github.com/magenta/ddsp/blob/4472de03a0a8e66874ecc3c1b841153e83a4cb0f/ddsp/spectral_ops.py#L267-L273

I noticed that f0 in gansynth_subset provided via tensorflow_dataset is calculated with this bug. Fortunately, the impact of the bug is not so large. I've checked some examples (not all) and about 1.2% values in each example are wrong.

**Comment by jesseengel** [comment]
Thanks for letting us know. We'll try to update the crepe version and nsynth dataset when we can.
