### ISSUE TITLE
Will this library work with pytorch?

### ISSUE THREAD

**Issue by lidh15** [magenta/ddsp#6]
Hi, DDSP seems to be quite helpful to my project, but I'm using PyTorch rather than TensorFlow, will it work with PyTorch?

**Comment by jesseengel** [comment]
The code in this repo currently only uses TensorFlow (what we use for research atm), so it won't run with PyTorch. That said, we've spent some time trying to create nice clean apis and structure things well, so we're not opposed to integrating a parallel PyTorch implementation, but don't have the resources to develop and test it ourselves.
