### ISSUE TITLE
train_autoencoder demo: issue installing pip dependencies

### ISSUE THREAD

**Issue by ameyakamat21** [magenta/ddsp#70]
![image](https://user-images.githubusercontent.com/3302501/78459865-06760000-7671-11ea-8899-d5f27b536a46.png)

Running into an issue running the block that installs dependencies:
```
ERROR: pydrive 1.3.1 has requirement oauth2client>=4.0.0, but you'll have oauth2client 3.0.0 which is incompatible.
ERROR: google-api-python-client 1.7.12 has requirement httplib2<1dev,>=0.17.0, but you'll have httplib2 0.12.0 which is incompatible.
ERROR: chainer 6.5.0 has requirement typing<=3.6.6, but you'll have typing 3.7.4.1 which is incompatible.
ERROR: chainer 6.5.0 has requirement typing-extensions<=3.6.6, but you'll have typing-extensions 3.7.4.2 which is incompatible.
```
The timbre transfer colab worked fine for me. 

Thank you for your work on these colab demos. I find them super useful.

**Comment by kcbuilder01** [comment]
Running into the same, problem as well. I’m thinking it didn’t allow me to download a proper checkpoint folder from the autoencoder Colab. Otherwise great work by you guys

**Comment by jesseengel** [comment]
Hmm, I'm seeing this too, I think it's new because they updated the default colab dependencies. I just ran both demos completely on Friday though and they seem to work fine (including downloading a checkpoint folder), so I _think_ it's not creating any bugs at the moment, but happy to hear otherwise.

**Comment by ameyakamat21** [comment]
Ah you're right, no bugs due to this.

**Comment by jesseengel** [comment]
fwiw, these went away when I updated the pip package.

**Comment by kcbuilder01** [comment]
Ok thanks Jesse
