### ISSUE TITLE
Floating point problem in compute_f0

### ISSUE THREAD

**Issue by kureta** [magenta/ddsp#73]
In `ddsp.spectral_ops.compute_f0`, when `len(audio)` is `1025253` and `sample_rate` is `16000`, `n_samples`, which is equivalent to `1025253 / 16000 * 16000` becomes `1025252.9999999999`, which then causes the assertion further down to fail (`assert n_padding % 1 == 0`).

**Comment by hubertsiuzdak** [comment]
Seems to be resolved in https://github.com/magenta/ddsp/pull/57. It is still not merged though so you can checkout [test_302135418](https://github.com/magenta/ddsp/tree/test_302135418) branch for now.

**Comment by jesseengel** [comment]
Sorry about the delay, #57 is still slowly going through the process of internal review, but thanks for the patience given all the craziness these days.

**Comment by jesseengel** [comment]
I think we finally got this in, and should be handled by #102
