### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by kcbuilder01** [magenta/ddsp#74]
Successfully cloned the repo to my saturn cloud jupyter notebook but I've run into a problem. The buttons and interactive displays dont show up in jupyter like they do in colab. IS there a workaround I can implement? Please help, love what you guys are doing so far. thanks

**Comment by jesseengel** [comment]
Unfortunately the forms (interactive displays) are a feature that I think is only available in colab. However, the code should run the  same, you just have to edit the variables manually at the top of each cell.

**Comment by kcbuilder01** [comment]
Thanks Jesse. Quick question, which model “DDSP” or “NSynth” is better for timbre transfer in your opinion? Been following both of your projects for a while. Super impressed

**Comment by kcbuilder01** [comment]
Or not only timbre transfer but interpolating between two timbres?

**Comment by jesseengel** [comment]
DDSP is much more efficient / bang for your computational buck, and should
do better for timbre interpolation, although we haven't focused as much on
that yet.

**Comment by kcbuilder01** [comment]
Awesome. I’ll see what I can build out. Thanks
