### ISSUE TITLE
Using ddsp_prepare_tfrecord with different 'example_secs' values than default

### ISSUE THREAD

**Issue by barisbozkurt** [magenta/ddsp#75]
Hi, I tried using various 'example_secs' values for ddsp_prepare_tfrecord to find a way to resynthesise complete audio recordings having different lengths. Basically I am trying to train the autoencoder with a collection of train files and then feed test audio files to see how well the autoencoder can perform copy-synthesis with unseen data.

Using the default values:
    --example_secs=4 \
    --sliding_window_hop_secs=1 \
the process ends without problems but of course with chunks of data sized as 4 seconds. 

I tried with various other settings such as:
    --example_secs=0 \
(to keep entire file)

    --example_secs=8 \
    --sliding_window_hop_secs=2 \
etc...
In creation the tfrecords file, no error message is printed and the file is created as expected. 

However trying to read/consume data(the tfrecords file produced), all settings other than the default returned with the following error::

InvalidArgumentError: Key: f0_confidence.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]

Any suggestions to keep original length of data while packing in tfrecords format?

**Comment by adarob** [comment]
You'll need to change set the `example_secs` appropriately in the `TFRecordProvider` for this to work.
For example, you can use a flag like `--gin_param='TFRecordProvider.example_secs = 8'` or add that setting to your gin config file.

**Comment by barisbozkurt** [comment]
Thanks Adarob, do you mean the use of of a fixed and same length for train and test files is a must for this experiment?

**Comment by adarob** [comment]
I believe it is possible to use a different length at inference time. @jesseengel to confirm. As for training, a fixed length is required by the data pipeline, but could probably be relaxed if necessary.

**Comment by barisbozkurt** [comment]
That's exactly my problem, I use fixed length (example 4 secs) during training. No problem in re-synthesizing train chunks of 4 seconds. Then I have a bunch of test files(from the same instrument) at various lengths. I would like to feed them to the autoencoder forward process (without running the feedback loop for training). This way I would like to check the analysis-synthesis quality of the trained network comparing audio files by listening to them (original versus resynthesized).  Thanks

**Comment by jesseengel** [comment]
This is possible at the moment, although not the most elegant. 


For a single case we do this in the [timbre_transfer](https://github.com/magenta/ddsp/blob/master/ddsp/colab/demos/timbre_transfer.ipynb) demo, by just reseting the values with gin.
```
# Ensure dimensions and sampling rates are equal
time_steps_train = gin.query_parameter('DefaultPreprocessor.time_steps')
n_samples_train = gin.query_parameter('Additive.n_samples')
hop_size = int(n_samples_train / time_steps_train)

time_steps = int(audio.shape[1] / hop_size)
n_samples = time_steps * hop_size

gin_params = [
    'Additive.n_samples = {}'.format(n_samples),
    'FilteredNoise.n_samples = {}'.format(n_samples),
    'DefaultPreprocessor.time_steps = {}'.format(time_steps),
]

with gin.unlock_config():
  gin.parse_config(gin_params)
```

However I would recommend creating a new dataset out of your test examples (cut into overlapping fixed lengths) and then reassembling them after the fact to listen to the whole sample together. This is due to a known issue with long samples (10+ seconds) where float32 errors accumulate in the sinusoidal oscillators.

**Comment by barisbozkurt** [comment]
Thanks Jesse. I thought using a long enough fixed length for both train and test could be a simpler solution (rather than rejoining segments, one could crop a longer).
 
So I was trying to have everything at 8 seconds length. I observed there exists another parameter window_secs set default as 4 in prepare_tfrecord_lib.py (line 110) and it seems a user set example_secs value (other than 4) would not be reflected there. Could there be a missing link between window_secs and example_secs?

Has anyone trained the auto_encoder with segment lengths other than 4 seconds?

**Comment by voodoohop** [comment]
With 2 seconds it seems to be working fine.

**Comment by jesseengel** [comment]
@barisbozkurt , the examples_secs in prepare_tfrecord_lib.py should be set by the flag, so as long as you make the dataset with 8 second long examples `--example_secs=8` and then change your gin parameters / file too you should be good to go.

**Comment by barisbozkurt** [comment]
Thanks for the comments Adarob, Jesse and Voodoohop. I have not completely solved my problem but I guess that's something to be done on my side
