### ISSUE TITLE
Issue with training model

### ISSUE THREAD

**Issue by hbrown1994** [magenta/ddsp#92]
![Screen Shot 2020-05-06 at 6 41 39 PM](https://user-images.githubusercontent.com/42399973/81239046-4eb67400-8fc9-11ea-997d-e7f7ab21362a.png)

Hi all! I'm really excited about using this library.

When trying to train my own auto-encoder model, I get the following error shown in this screenshot. Anything I might be doing wrong here?

Thanks!

**Comment by fletcherist** [comment]
Yes I've got stacked with this just yesterday. For a quick fix please go to the folder
`/usr/local/lib/python3.6/dist-packages/ddsp/training/ddsp_run.py` in you colab notebook. Download file `ddsp_run.py`, open it with an editor, and comment lines from 137 to 141 just like this (pls look at screenshot attached). Then upload updated version of this file to the ``/usr/local/lib/python3.6/dist-packages/ddsp/training/` by simple dragndrop and restart cell. After that it should start training process. 
<img width="641" alt="Screen Shot 2020-05-07 at 2 50 23 AM" src="https://user-images.githubusercontent.com/15146860/81239799-7c71dc00-900e-11ea-9627-9a77b8942e95.png">

In a few hours, I'll provide more info on how to fix the issue via sending PR

**Comment by hbrown1994** [comment]
Awesome! Its working for me now.

Thanks for your help!

**Comment by jesseengel** [comment]
Thanks for the response @fletcherist! I'm actually working on a fix right now if that helps.

**Comment by fletcherist** [comment]
@jesseengel also for this [train_autoencoder.ipynb](https://github.com/magenta/ddsp/blob/master/ddsp/colab/demos/train_autoencoder.ipynb) notebook: I've found a missing link to the timbre shifting notebook at the end, and I fixed it in #94 Can you please take a [look](https://github.com/magenta/ddsp/pull/94)?

_btw_ thanks for an amazing pipeline and research. I'm looking forward to wrap it somehow in Max for Ableton Live plugin to modulate realistic orchestra sounds via sin through this model

**Comment by jesseengel** [comment]
Thanks! I fixed this in #95, which actually reverts to an earlier change. There are just a few different versions, (internal, git, pypi, releases) so I forgot to update, and did a hasty 'fix' that actually broke things. Should work now.

Realtime would be great for sure :). You can actually go faster than that by writing in TFLite (making a VST in JUCE). We started down that path, but don't have someone to work on it at the moment.

**Comment by jesseengel** [comment]
Yup, I ran the notebook again and works fine now.
