### ISSUE TITLE
Trouble recreating solo violin dataset

### ISSUE THREAD

**Issue by erl-j** [magenta/ddsp#97]
Hello!

Thank you for all your great work on this library.

I want to reproduce the solo violin experiment from the library. 

I've downloaded the mp3s (the wavs are paywalled unfortunately) of the pieces performed by John Gardner from the link provided in the paper.

However, I'm getting the following error when I run ddsp_prepare_tfrecord.

````
 File "/home/myuser/.local/lib/python3.7/site-packages/ddsp/spectral_ops.py", line 261, in compute_f0
    assert n_padding % 1 == 0
RuntimeErrar: AssertionError [while running 'Map(_add_f0_estimate)']
````

This seems to be an issue with some of the clips, like **V. Sarabande.mp3**.

Thank you!

**Comment by jesseengel** [comment]
Sorry, we should have a more helpful error message:

I think what's happening is the frame_rate is not evenly dividing the sample_rate, which is giving you then a fractional amount of padding to apply. Try downsampling the audio using something like `sox` to 16kHz, and make sure sample_rate is 16000 and frame_rate divides it evenly, like 250.

```python
def compute_f0(audio, sample_rate, frame_rate, viterbi=True):
  """Fundamental frequency (f0) estimate using CREPE.

  This function is non-differentiable and takes input as a numpy array.
  Args:
    audio: Numpy ndarray of single audio example. Shape [audio_length,].
    sample_rate: Sample rate in Hz.
    frame_rate: Rate of f0 frames in Hz.
    viterbi: Use Viterbi decoding to estimate f0.

  Returns:
    f0_hz: Fundamental frequency in Hz. Shape [n_frames,].
    f0_confidence: Confidence in Hz estimate (scaled [0, 1]). Shape [n_frames,].
  """

  # Pad end so that `n_frames = n_sec * frame_rate`.
  # We compute this using the CREPE model's sample rate and then convert back to
  # our sample rate.
  n_secs = len(audio) / sample_rate
  n_samples = n_secs * _CREPE_SAMPLE_RATE
  hop_size = sample_rate / frame_rate
  frame_size = _CREPE_FRAME_SIZE
  n_frames = np.ceil(n_secs * frame_rate)
  n_samples_padded = (n_frames - 1) * hop_size + frame_size
  n_padding = (n_samples_padded - n_samples) * sample_rate / _CREPE_SAMPLE_RATE
  assert n_padding % 1 == 0
```

Also, for what it's worth, I restricted to monophonic pieces for training, which doesn't include V. Sarabande I think. From the paper:
Five pieces by John Garner (II. Double, III. Corrente, IV. Double Presto, VI. Double, VIII. Double) from https://musopen.org/music/13574-violin-partita-no-1-bwv-1002/

They must have added a paywall recently. Although I seem to be able to download all the files for the paper in mp3 form fine.

**Comment by erl-j** [comment]
Perfect! Thank you!
